/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '8/1/16 9:57 AM' with Gradle 2.13
 *
 * @author sbyan, @date 8/1/16 9:57 AM
 */
class Library {
    boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.print("ag");
    }
}
